import csv
import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PYTHON_DIR = ROOT / "python"
sys.path.insert(0, str(PYTHON_DIR))

from comsol_opt.config_io import dump_data, load_config, load_json
from comsol_opt.flow import prepare_parameter_txt_set, run_flow
from comsol_opt.calibration import parameter_regularization_loss
from comsol_opt.loss import compute_loss_from_rows
from comsol_opt.backends import make_backend
from comsol_opt.parameter_txt import ParameterTxtSet
from comsol_opt.schemas import RveResult, StepInput, WaferState


class ParameterTxtSetTests(unittest.TestCase):
    def test_updates_struct_stress_and_temp_parameter_files(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            struct = root / "struct.txt"
            stress = root / "stress.txt"
            temp = root / "temp.txt"
            struct.write_text("pillar_diameter\t120e-9[m]\tpillar diameter\n", encoding="utf-8")
            stress.write_text(
                "sigma_feol_x\t180e6[Pa]\tFEOL x stress\nsigma_w_fill\t500e6[Pa]\tW fill stress\n",
                encoding="utf-8",
            )
            temp.write_text("process_temp\t25[degC]\tprocess temperature\n", encoding="utf-8")

            txt_set = ParameterTxtSet(
                files={"struct": struct, "stress": stress, "temp": temp},
                mappings={
                    "geometry.pillar_diameter": {"file": "struct", "name": "pillar_diameter", "unit": "m"},
                    "FEOL.sigma_init_x": {"file": "stress", "name": "sigma_feol_x", "unit": "Pa"},
                    "W.sigma_fill": {"file": "stress", "name": "sigma_w_fill", "unit": "Pa"},
                    "process.temperature_C": {"file": "temp", "name": "process_temp", "unit": "degC"},
                    "missing.param": {"file": "stress", "name": "missing_param", "unit": "Pa"},
                },
            )

            output = root / "trial_params"
            paths = txt_set.write_trial_files(
                output,
                {
                    "geometry.pillar_diameter": 125e-9,
                    "FEOL.sigma_init_x": 175e6,
                    "W.sigma_fill": 600e6,
                    "process.temperature_C": 300,
                    "missing.param": 42,
                },
            )

            self.assertEqual(set(paths), {"struct", "stress", "temp"})
            self.assertIn("pillar_diameter\t1.25e-07[m]\tpillar diameter", paths["struct"].read_text(encoding="utf-8"))
            stress_text = paths["stress"].read_text(encoding="utf-8")
            self.assertIn("sigma_feol_x\t175000000.0[Pa]\tFEOL x stress", stress_text)
            self.assertIn("sigma_w_fill\t600000000.0[Pa]\tW fill stress", stress_text)
            self.assertIn("missing_param\t42[Pa]\tgenerated by comsol_opt", stress_text)
            self.assertIn("process_temp\t300[degC]\tprocess temperature", paths["temp"].read_text(encoding="utf-8"))


class WorkflowIntegrationTests(unittest.TestCase):
    def test_mock_flow_preserves_rve_inheritance_and_asi_template_switch(self):
        with tempfile.TemporaryDirectory() as tmp:
            run_root = Path(tmp) / "runs"
            cmd = [
                sys.executable,
                str(ROOT / "python" / "run_flow.py"),
                "--backend",
                "mock",
                "--run-id",
                "mock_test",
                "--runs-root",
                str(run_root),
            ]
            completed = subprocess.run(cmd, cwd=ROOT, text=True, capture_output=True, check=True)
            self.assertIn("Completed 2 steps", completed.stdout)

            run_dir = run_root / "mock_test"
            s02 = json.loads((run_dir / "S02" / "state_out.json").read_text(encoding="utf-8"))
            self.assertEqual(s02["rve"]["device_aux"]["source_step"], "S00")
            self.assertEqual(s02["rve"]["mat2"]["source_step"], "S00")
            self.assertEqual(s02["rve"]["mat4"]["source_step"], "S00")
            self.assertEqual(s02["rve"]["die"]["source_step"], "S02")
            self.assertEqual(set(s02["rve"]), {"device_main", "device_aux", "onon_device", "mat1", "mat2", "mat3", "mat4", "die"})

            s02_input = json.loads((run_dir / "S02" / "step_input.json").read_text(encoding="utf-8"))
            self.assertEqual([node["id"] for node in s02_input["nodes"][:3]], ["device_main", "device_aux", "onon_device"])
            self.assertEqual(
                s02_input["parameter_txt_order"],
                ["global_params", "S02_trench_etch_params", "calibration_override"],
            )

            manifest = json.loads((run_dir / "S02" / "manifest.json").read_text(encoding="utf-8"))
            self.assertEqual(manifest["nodes"]["device_aux"]["action"], "inherit")
            self.assertEqual(manifest["nodes"]["device_aux"]["source_step"], "S00")
            self.assertTrue((run_dir / "S02" / "mat1_rve.json").exists())
            self.assertTrue((run_dir / "S02" / "wafer_result.json").exists())

            with (run_dir / "summary.csv").open(newline="", encoding="utf-8") as handle:
                rows = list(csv.DictReader(handle))
            self.assertEqual(len(rows), 2)
            loss = compute_loss_from_rows(rows, scale_x=30.0, scale_y=30.0)
            self.assertGreater(loss["loss"], 0.0)

    def test_dryrun_generates_step_inputs_without_results(self):
        with tempfile.TemporaryDirectory() as tmp:
            run_root = Path(tmp) / "runs"
            cmd = [
                sys.executable,
                str(ROOT / "python" / "run_flow.py"),
                "--backend",
                "dryrun",
                "--run-id",
                "dryrun_test",
                "--runs-root",
                str(run_root),
            ]
            subprocess.run(cmd, cwd=ROOT, text=True, capture_output=True, check=True)
            run_dir = run_root / "dryrun_test"
            self.assertTrue((run_dir / "S00" / "step_input.json").exists())
            self.assertFalse((run_dir / "S00" / "state_out.json").exists())

    def test_mock_calibration_writes_history_and_best_params_without_optuna(self):
        with tempfile.TemporaryDirectory() as tmp:
            run_root = Path(tmp) / "runs"
            cmd = [
                sys.executable,
                str(ROOT / "python" / "calibration_optuna.py"),
                "--backend",
                "mock",
                "--run-id",
                "calib_test",
                "--runs-root",
                str(run_root),
                "--n-trials",
                "2",
            ]
            completed = subprocess.run(cmd, cwd=ROOT, text=True, capture_output=True, check=True)
            self.assertIn("best_loss=", completed.stdout)
            calib_dir = run_root / "calib_test"
            self.assertTrue((calib_dir / "calibration_history.csv").exists())
            self.assertTrue((calib_dir / "best_params.yaml").exists())
            self.assertTrue((calib_dir / "best_summary.csv").exists())

    def test_staged_calibration_writes_per_stage_outputs_and_carries_params(self):
        with tempfile.TemporaryDirectory() as tmp:
            run_root = Path(tmp) / "runs"
            cmd = [
                sys.executable,
                str(ROOT / "python" / "calibration_optuna.py"),
                "--backend",
                "mock",
                "--run-id",
                "staged_test",
                "--runs-root",
                str(run_root),
                "--n-trials",
                "2",
                "--optimizer",
                "random",
                "--mode",
                "staged",
                "--stages",
                "G0_init,G2_trench_release",
            ]
            completed = subprocess.run(cmd, cwd=ROOT, text=True, capture_output=True, check=True)
            self.assertIn("completed_stages=2", completed.stdout)

            calib_dir = run_root / "staged_test"
            g0 = calib_dir / "out" / "S00_G0_init"
            g1 = calib_dir / "out" / "S02_G2_trench_release"
            self.assertTrue((g0 / "stage.log").exists())
            self.assertTrue((g0 / "best_params.yaml").exists())
            self.assertTrue((g0 / "best_summary.csv").exists())
            self.assertTrue((g1 / "stage.log").exists())
            self.assertTrue((g1 / "best_params.yaml").exists())
            self.assertTrue((calib_dir / "out" / "final_params.yaml").exists())

            g0_params = load_config(g0 / "best_params.yaml")
            g1_trial_params = load_config(g1 / "trials" / "trial_0000" / "params_trial.yaml")
            self.assertEqual(g1_trial_params["FEOL"], g0_params["FEOL"])

            g1_log = (g1 / "stage.log").read_text(encoding="utf-8")
            self.assertIn("stage=G2_trench_release", g1_log)
            self.assertIn("params=release.trench_etch_ONON", g1_log)
            self.assertTrue((g1 / ".cache").exists())
            self.assertFalse((g1 / "trials" / "trial_0000" / "flow" / ".cache").exists())

    def test_mock_flow_can_skip_wafer_solve_and_preserve_previous_result(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            flow = load_config(ROOT / "configs" / "flow.yaml")
            flow["steps"] = [dict(flow["steps"][0])]
            flow["steps"][0]["run_wafer"] = False
            flow_path = root / "flow.yaml"
            dump_data(flow_path, flow)
            result = run_flow(
                flow_path=flow_path,
                params_path=ROOT / "configs" / "params_nominal.yaml",
                experiment_path=ROOT / "exp" / "bow_experiment.csv",
                backend=make_backend("mock"),
                run_id="skip_wafer",
                runs_root=root / "runs",
                repo_root=ROOT,
            )

            step_dir = result["run_dir"] / "S00"
            state = load_json(step_dir / "state_out.json")
            step_result = load_json(step_dir / "step_result.json")
            self.assertEqual(state["wafer_result"]["bow_x_um"], 0.0)
            self.assertEqual(state["history"], [])
            self.assertTrue(step_result["wafer_skipped"])

    def test_mock_flow_rejects_unknown_process_update_rule(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            flow = load_config(ROOT / "configs" / "flow.yaml")
            flow["steps"] = [dict(flow["steps"][0])]
            flow["steps"][0]["update_rule"] = "unknown_rule"
            flow_path = root / "flow.yaml"
            dump_data(flow_path, flow)
            with self.assertRaises(ValueError):
                run_flow(
                    flow_path=flow_path,
                    params_path=ROOT / "configs" / "params_nominal.yaml",
                    experiment_path=ROOT / "exp" / "bow_experiment.csv",
                    backend=make_backend("mock"),
                    run_id="bad_rule",
                    runs_root=root / "runs",
                    repo_root=ROOT,
                )


class ConfigTests(unittest.TestCase):
    def test_default_flow_config_loads_as_yaml(self):
        flow = load_config(ROOT / "configs" / "flow.yaml")
        self.assertEqual(flow["steps"][0]["id"], "S00")
        self.assertEqual(flow["steps"][-1]["id"], "S02")
        self.assertIn("global", flow)
        self.assertEqual(flow["steps"][0]["config"], "configs/steps/S00_init.yaml")

    def test_config_files_are_real_yaml_and_flow_is_readable(self):
        for path in (ROOT / "configs").glob("*.yaml"):
            text = path.read_text(encoding="utf-8")
            self.assertFalse(text.lstrip().startswith("{"), path.name)
        self.assertTrue(all(len(line) <= 120 for line in (ROOT / "configs" / "flow.yaml").read_text(encoding="utf-8").splitlines()))

    def test_layered_flow_expands_step_dag_and_txt_parameters(self):
        from comsol_opt.flow_runner import load_flow_definition

        flow = load_flow_definition(ROOT / "configs" / "flow.yaml", ROOT)
        self.assertEqual([step["id"] for step in flow["steps"]], ["S00", "S02"])
        s02 = flow["steps"][1]
        self.assertEqual(s02["nodes"][1]["action"], "inherit")
        self.assertEqual(s02["parameters"]["release"]["trench_etch_ONON"], 0.75)
        self.assertEqual(s02["parameter_txt_order"], ["global_params", "S02_trench_etch_params", "calibration_override"])

    def test_default_paths_are_flattened(self):
        flow = load_config(ROOT / "configs" / "templates.yaml")
        template_paths = []
        for section in flow["templates"].values():
            for spec in section.values():
                template_paths.append(spec["path"])
        self.assertTrue(template_paths)
        self.assertTrue(all(path.startswith("models/templates/") for path in template_paths))

    def test_parameter_map_config_drives_txt_mapping(self):
        parameter_map = load_config(ROOT / "configs" / "parameter_map.yaml")
        txt_set = prepare_parameter_txt_set(ROOT)
        mapping = parameter_map["parameters"]["W.sigma_fill"]
        self.assertEqual(mapping["file"], "stress")
        self.assertEqual(mapping["txt_name"], "sigma_w_fill")
        self.assertEqual(txt_set.mappings["W.sigma_fill"]["file"], "stress")
        self.assertEqual(txt_set.mappings["W.sigma_fill"]["name"], "sigma_w_fill")

    def test_calibration_space_has_prior_scale_and_units(self):
        space = load_config(ROOT / "configs" / "calibration_space.yaml")
        missing = []
        for group in space["groups"]:
            for spec in group["params"]:
                for key in ("prior", "scale", "unit"):
                    if key not in spec:
                        missing.append((group["name"], spec["key"], key))
        self.assertEqual(missing, [])

    def test_prior_scale_regularization_uses_normalized_distance(self):
        specs = [
            {"key": "x", "prior": 10.0, "scale": 2.0},
            {"key": "nested.y", "prior": 5.0, "scale": 5.0},
        ]
        params = {"x": 12.0, "nested": {"y": 0.0}}
        self.assertEqual(parameter_regularization_loss(params, specs), 2.0)

    def test_comsol_worker_draft_contains_expected_api_shape(self):
        worker = ROOT / "java" / "ComsolStepWorker.java"
        text = worker.read_text(encoding="utf-8")
        self.assertIn("ModelUtil.load", text)
        self.assertIn("model.param().loadFile", text)
        self.assertIn(".study(", text)
        self.assertIn(".run()", text)
        self.assertIn("gev1", text)
        self.assertIn("gmevescp2", text)
        self.assertIn("run_wafer", text)

    def test_flow_responsibilities_are_split_into_focused_modules(self):
        import comsol_opt.flow_runner as flow_runner
        import comsol_opt.step_input as step_input
        import comsol_opt.summary as summary

        self.assertTrue(callable(flow_runner.run_flow))
        self.assertTrue(callable(step_input.build_step_input))
        self.assertTrue(callable(summary.write_summary))

    def test_config_io_exposes_generic_dump_data_for_yaml_and_json(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            yaml_path = root / "data.yaml"
            json_path = root / "data.json"
            dump_data(yaml_path, {"b": 2, "a": 1})
            dump_data(json_path, {"b": 2, "a": 1})
            self.assertEqual(load_config(yaml_path), {"a": 1, "b": 2})
            self.assertEqual(load_json(json_path), {"a": 1, "b": 2})

    def test_schema_validation_rejects_incomplete_rve_and_step_input(self):
        valid_rve = RveResult.from_dict(
            {
                "valid": True,
                "active": True,
                "source_step": "S01",
                "source_model": "model",
                "rho": 1.0,
                "stress_eff": {"sxx": 1.0, "syy": 2.0},
                "D": [[0.0] * 6 for _ in range(6)],
                "meta": {},
            }
        )
        self.assertEqual(valid_rve.source_step, "S01")
        valid_state = WaferState.from_dict(
            {
                "step_id": "S01",
                "step_name": "step",
                "wafer_result": {"bow_x_um": 0.0, "bow_y_um": 0.0, "kx": 0.0, "ky": 0.0},
                "device_rves": {"device_default": valid_rve_dict()},
                "wafer_inputs": {"mat1": valid_rve_dict()},
                "materials_state": {},
                "geometry_state": {},
                "history": [],
            }
        )
        self.assertEqual(valid_state.step_id, "S01")
        with self.assertRaises(ValueError):
            RveResult.from_dict({"D": [[0.0]]})
        with self.assertRaises(ValueError):
            StepInput.from_dict({"step_id": "S00"})


def valid_rve_dict():
    return {
        "valid": True,
        "active": True,
        "source_step": "S01",
        "source_model": "model",
        "rho": 1.0,
        "stress_eff": {"sxx": 1.0, "syy": 2.0},
        "D": [[0.0] * 6 for _ in range(6)],
        "meta": {},
    }


if __name__ == "__main__":
    unittest.main()
