from pathlib import Path
import re


class ParameterTxtSet:
    """Update COMSOL parameter txt files while preserving simple line style."""

    def __init__(self, files, mappings):
        self.files = {key: Path(value) for key, value in files.items()}
        self.mappings = mappings

    def write_trial_files(self, output_dir, values):
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        output_paths = {}
        for group, src in self.files.items():
            dst = output_dir / src.name
            dst.write_text(src.read_text(encoding="utf-8"), encoding="utf-8")
            output_paths[group] = dst

        by_file = {}
        for dotted_key, value in values.items():
            mapping = self.mappings.get(dotted_key)
            if mapping is None:
                continue
            by_file.setdefault(mapping["file"], {})[mapping["name"]] = {
                "value": value,
                "unit": mapping.get("unit", ""),
            }

        for group, updates in by_file.items():
            path = output_paths[group]
            path.write_text(_update_parameter_text(path.read_text(encoding="utf-8"), updates), encoding="utf-8")
        return output_paths


def _format_value(value):
    return str(value)


def _update_parameter_text(text, updates):
    remaining = dict(updates)
    lines = []
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or stripped.startswith("%"):
            lines.append(line)
            continue
        if "=" in line:
            left, _right = line.split("=", 1)
            name = left.strip()
            if name in remaining:
                update = remaining.pop(name)
                lines.append(f"{left.rstrip()} = {_format_value(update['value'])}")
            else:
                lines.append(line)
            continue

        match = re.match(r"^(\s*)(\S+)(\s+)(\S+)(.*)$", line)
        if not match:
            lines.append(line)
            continue
        prefix, name, sep, old_value_token, suffix = match.groups()
        if name in remaining:
            update = remaining.pop(name)
            unit_suffix = _unit_suffix(old_value_token, update.get("unit", ""))
            lines.append(f"{prefix}{name}{sep}{_format_value(update['value'])}{unit_suffix}{suffix}")
        else:
            lines.append(line)
    for name, update in remaining.items():
        unit_suffix = f"[{update['unit']}]" if update.get("unit") else ""
        lines.append(f"{name}\t{_format_value(update['value'])}{unit_suffix}\tgenerated by comsol_opt")
    return "\n".join(lines) + "\n"


def _unit_suffix(value_token, configured_unit):
    match = re.search(r"(\[.*\])$", value_token)
    if match:
        return match.group(1)
    if configured_unit:
        return f"[{configured_unit}]"
    return ""


def parse_parameter_txt(path):
    """Parse COMSOL parameter txt rows into name -> expression metadata."""
    params = {}
    for line in Path(path).read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or stripped.startswith("%"):
            continue
        parts = stripped.split()
        if len(parts) < 2:
            continue
        name = parts[0]
        expression = parts[1]
        params[name] = {
            "expression": expression,
            "value": expression_to_float(expression),
            "description": " ".join(parts[2:]),
        }
    return params


def parse_parameter_txt_files(paths):
    merged = {}
    for path in paths:
        merged.update(parse_parameter_txt(path))
    return merged


def expression_to_float(expression):
    """Convert simple COMSOL numeric expressions like 100[MPa] to SI-ish floats."""
    match = re.match(r"^\s*([+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?)(?:\[(.+)\])?\s*$", str(expression))
    if not match:
        raise ValueError(f"Unsupported parameter expression: {expression}")
    value = float(match.group(1))
    unit = match.group(2)
    multipliers = {
        None: 1.0,
        "": 1.0,
        "Pa": 1.0,
        "MPa": 1.0e6,
        "GPa": 1.0e9,
        "m": 1.0,
        "nm": 1.0e-9,
        "um": 1.0e-6,
        "kg/m^3": 1.0,
        "degC": 1.0,
    }
    return value * multipliers.get(unit, 1.0)
