{
  "parameter_files": {
    "struct": "params/struct.txt",
    "stress": "params/stress.txt",
    "temp": "params/temp.txt"
  },
  "parameters": {
    "geometry.pillar_diameter": {
      "file": "struct",
      "txt_name": "pillar_diameter",
      "unit": "m"
    },
    "FEOL.sigma_init_x": {
      "file": "stress",
      "txt_name": "sigma_feol_x",
      "unit": "Pa"
    },
    "FEOL.sigma_init_y": {
      "file": "stress",
      "txt_name": "sigma_feol_y",
      "unit": "Pa"
    },
    "ONON.sigma_O_base": {
      "file": "stress",
      "txt_name": "sigma_o_base",
      "unit": "Pa"
    },
    "ONON.sigma_N_base": {
      "file": "stress",
      "txt_name": "sigma_n_base",
      "unit": "Pa"
    },
    "release.trench_etch_ONON": {
      "file": "stress",
      "txt_name": "release_trench_etch_onon",
      "unit": ""
    },
    "release.dpillar_form_ONON": {
      "file": "stress",
      "txt_name": "release_dpillar_form_onon",
      "unit": ""
    },
    "release.mat_remove_ONON": {
      "file": "stress",
      "txt_name": "release_mat_remove_onon",
      "unit": ""
    },
    "release.final_ONON": {
      "file": "stress",
      "txt_name": "release_final_onon",
      "unit": ""
    },
    "Ox.sigma_trench_fill": {
      "file": "stress",
      "txt_name": "sigma_ox_trench_fill",
      "unit": "Pa"
    },
    "pillar_dep.dep1.sigma_init": {
      "file": "stress",
      "txt_name": "sigma_dep1",
      "unit": "Pa"
    },
    "pillar_dep.dep2.sigma_init": {
      "file": "stress",
      "txt_name": "sigma_dep2",
      "unit": "Pa"
    },
    "pillar_dep.dep3.sigma_init": {
      "file": "stress",
      "txt_name": "sigma_dep3",
      "unit": "Pa"
    },
    "pillar_dep.dep4.sigma_init": {
      "file": "stress",
      "txt_name": "sigma_dep4",
      "unit": "Pa"
    },
    "pillar_dep.dep5.sigma_init": {
      "file": "stress",
      "txt_name": "sigma_dep5",
      "unit": "Pa"
    },
    "aSi.sigma": {
      "file": "stress",
      "txt_name": "sigma_asi",
      "unit": "Pa"
    },
    "W.sigma_fill": {
      "file": "stress",
      "txt_name": "sigma_w_fill",
      "unit": "Pa"
    },
    "process.temperature_C": {
      "file": "temp",
      "txt_name": "process_temp",
      "unit": "degC"
    }
  }
}
